### ISSUE TITLE
Error with plugins, from am3yrus

### ISSUE THREAD

**Issue by francysuri** [janrueth/SiriServerPlugins#2]
hi, i have a problem with some plugins, they fail loading and returns this error:
(i followed am3yrus guide to install siriserver and it returns this error, please help)

INFO Loading Plugin Framework
Traceback (most recent call last):
File "/usr/lib/python2.6/logging/init.py", line 776, in emit
msg = self.format(record)
File "/usr/lib/python2.6/logging/init.py", line 654, in format
return fmt.format(record)
File "/usr/lib/python2.6/logging/init.py", line 454, in format
s = s + record.exc_text.decode(sys.getfilesystemencoding())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 287: ordinal not in range(128)

**Comment by janrueth** [comment]
did you copy paste the plugin from github?

**Comment by francysuri** [comment]
no, i just cloned the git and used am3yrus tar with plugins, he probably did... i wanted to translate to italian but if i get this even in english i can't go on... look at http://am3yrus.com/index.php/tutorials/10-siriserver-installation/6-siriserver-debian-squeeze-physical-or-virtual-machine

**Comment by francysuri** [comment]
@Eichhoernchen do you have something like skype or facebook to talk better? i can pay if you solve this problem

**Comment by janrueth** [comment]
I'm sorry, but the tutorial there is full of errors, also it isn't even my repository that is cloned. I can't see why your problems should be discussed here (this is not a help forum, go to www.ioshack.org/forums for such help). 

You can't copy paste the plugins on some operating systems as they have problems with UTF-8, so just download them directly and do not use your clipboard
