### ISSUE TITLE
phoneCall not working with latest core?

### ISSUE THREAD

**Issue by PenangKiD** [janrueth/SiriServerPlugins#4]
Anyone got any problem using the phoneCall plugin with the latest core? My problem is when I say on my phone to Siri 'Call Albert' then Siri reply 'Calling Albert iphone xx xxx xxx' then nothing happen. It's not calling Albert as it suppose to.

Please advice. TQ.

**Comment by janrueth** [comment]
hm, can you give debug output (start server with -ldebug) also are you using the current version from this git?

**Comment by PenangKiD** [comment]
Yes, I'm using the latest version core. Just checked it again with 'git pull'. The -ldebug gives a quite long log, can't copy all from my putty (no idea why the Copy all to clipboard don't work). Here are what I manage to get:

http://pastebin.com/jeLjY4F2

Hope it helps ..

**Comment by PenangKiD** [comment]
Today I reinstall my whole ubuntu server (without Apache,PHP5, mySQL) and git clone again core server and the plugins and it works! Well guess I mess up my server last time. Sry..
