### ISSUE TITLE
Open url

### ISSUE THREAD

**Issue by trevor403** [janrueth/SiriServerPlugins#5]
is there a way to open a url without as a request without answer function, like an http:// url or if possible a fb:// url?

**Comment by janrueth** [comment]
in general the command is there (UIObjects UIOpenLink) but siri on the iphone won't allow http:// links, you can only open preference menues and so on, it would be possible to patch this out using mobile substrate but in general you cannot open these kind of links.

(If you try, Siri will output something a long these lines to the console: "unsafe url detected")

**Comment by trevor403** [comment]
But can you use it to open app URLs like app://blah

**Comment by janrueth** [comment]
as I said... no :) You can as far as I know only open the settings menu through it. But try it

**Comment by trevor403** [comment]
Well I guess it's Theos coding time haha

**Comment by janrueth** [comment]
jep :)

**Comment by trevor403** [comment]
no, pyep
